### PR TITLE
New attack technique: Backdoor aws-auth ConfigMap

### PR DESCRIPTION
**Pull request by rileydakota**
### What does this PR do?

* New attack technique

### Motivation

* The aws-auth configmap is functionally similar to that of a resource policy, and a potential blindspot for cloud security teams who monitor external IAM/cross account access. Cross account roles are supported by this method - therefore it is susceptible to the same style of backdooring as other techniques here.

@christophetd added a disclaimer for now - I could also rename the technique to `eks-backdoor-awsauth` to indicate better that it will likely only apply to EKS installations (Or those who have installed the AWS Authenticator for Kubernetes)

We can also look to add an EKS Provider, but I only know of one other EKS specific technique at the current moment.

### CODE REVIEW

**Comment by rileydakota** [comment]
@christophetd would you also like for me to add doc changes with this? I just released that was missing

**Comment by christophetd** [comment]
As discussed in PM, this attack technique is too specific to EKS and doesn't apply to K8s environments in general, so we'll close the PR. We can revisit in the future

**Comment by rileydakota** [comment]
@christophetd thoughts on revisiting this given it surfaced in this blog in tldrsec: https://blog.calif.io/p/privilege-escalation-in-eks#§to-backdooring-the-eks-cluster

**Comment by christophetd** [comment]
Unfortunately I don't think EKS is a good fit for Stratus Red Team right now, at least not under the "K8s" platform - since it requires an EKS cluster (not a generic K8s one).

Let me tag it with "platform/eks" and see if it would make sense to add dedicated support? What do you think?

See also #344

**Pull request closed without merging**
