### PR TITLE
New attack technique: Spin up unusual EC2 instances

### PR DESCRIPTION
**Pull request by rollwagen**
### What does this PR do?

* New attack technique

### Motivation

Implement technique as mentioned in existing issue:

https://github.com/DataDog/stratus-red-team/issues/80

### Checklist

- [X ] The attack technique emulates a single attack step, not a full attack chain
- [X ] We have factual evidence & references that the attack technique was used by real malware, pentesters, or attackers
- [X] The attack technique makes no assumption about the state of the environment prior to warming it up

### CODE REVIEW

**Comment by christophetd** [comment]
As discussed on Twitter, I suggest we use a role that doesn't have the permissions to start new instances, so that it emulates the behavior without actually creating a bunch of expensive instances. Thoughts?

**Comment by christophetd** [comment]
I'm getting the following error:

```
Error while detonating attack technique aws.execution.ec2-launch-unusual-instances: expected ec2:RunInstances to return an access denied error, got instead: operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: a00d457e-f5ea-4561-86b2-27b1d6dd8155, api error VPCIdNotSpecified: No default VPC for this user. GroupName is only supported for EC2-Classic and default VPC.
```

We might need to create a VPC to make no assumption on the state of the AWS account, what do you think? Similarly to https://github.com/DataDog/stratus-red-team/blob/main/internal/attacktechniques/aws/execution/ec2-user-data/main.tf#L27

Otherwise I made a few minor updates to the code

**Comment by christophetd** [comment]
Addressed in [a26dc1f](https://github.com/DataDog/stratus-red-team/pull/134/commits/a26dc1ffe54d37675ec8b6727a564b894c8fd376) but I still get:

```
Error while detonating attack technique aws.execution.ec2-launch-unusual-instances: expected ec2:RunInstances to return an access denied error, got instead: operation error EC2: RunInstances, https response error StatusCode: 400, RequestID: b82b7af6-5486-4c93-8ed6-edec46e8bfe0, api error VcpuLimitExceeded: You have requested more vCPU capacity than your current vCPU limit of 0 allows for the instance bucket that the specified instance type belongs to. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit
```

We should use instance types that are runnable by default

**Comment by christophetd** [comment]
todo (@christophetd)

- [ ] Use minCount = 1

**Comment by rollwagen** [comment]
Thanks for the thoughts and feedback. Regarding

> We should use instance types that are runnable by default

it's a bit of a (difficult) balance act I'd say. If we want to stick to the "expensive-looking EC2 instances" as mentioned in the original issue, then you risk running into VcpuLimitExceeded; if we go towards instances that pretty much always run they are like rather standard non expensive looking ones.
On the detection side, it is mentioned in the attack technique that you need watch out for both RunInstances/Client.UnauthorizedOperation and VcpuLimitExceeded error codes. Personally, I'd leave it with the bigg(er) instance types. Alternative might be to adjust the attack (detonate) to try to launch two types of instances, a smaller one runnable by default, and an expensive big one.

**Pull request merged**
