### PR TITLE
docs: add asdf as way to install

### PR DESCRIPTION
**Pull request by vthiery**
### What does this PR do?

Document how to install stratus-red-team using [asdf](https://asdf-vm.com/).
I have also slightly changed how installation methods are listed for clarity. 

### Motivation

Using [asdf](https://asdf-vm.com/) and the [plugin I wrote for stratus-red-team](https://github.com/vthiery/asdf-stratus-red-team) is a convenient way to use / test different versions of stratus-red-team.

### Checklist

NA

### CODE REVIEW

**Comment by christophetd** [comment]
Thanks for the contribution! I'm happy to add asdf support, but I'd like to have the plugin repo as part of the same repo. Is there a way to add it e.g. in a subfolder?

**Comment by vthiery** [comment]
> Thanks for the contribution! I'm happy to add asdf support, but I'd like to have the plugin repo as part of the same repo. Is there a way to add it e.g. in a subfolder?

I believe that the "right" way to maintain asdf plugins is the way it is now: separate from the actual tool.
I have raised a PR to add the plugin to the plugins directory: https://github.com/asdf-vm/asdf-plugins/pull/971

If we want more assurance around the maintenance of the plugin, I am happy to transfer ownership to the [asdf--community ](https://github.com/asdf-community).

What do you think?

**Comment by christophetd** [comment]
https://github.com/asdf-vm/asdf-plugins/pull/971 is perfect! Let's wait for it to be merged and circle back here, thank you

**Comment by christophetd** [comment]
Transfering to asdf-community would be optimal, thanks oyu

**Comment by vthiery** [comment]
> Transfering to asdf-community would be optimal, thank you

Let me proceed with the transfer then and I will update this PR accordingly.

**Comment by christophetd** [comment]
Hi @vthiery, still eager to merge this, let me know when the transfer happens! Thanks

**Comment by vthiery** [comment]
Hi @christophetd, I'm still waiting on the asdf-community to initiate the transfer https://github.com/asdf-community/infrastructure/pull/149

**Comment by christophetd** [comment]
Thanks! I left a comment in the linked PR as well

**Comment by vthiery** [comment]
@christophetd the repository has been transferred.

**Comment by christophetd** [comment]
Thanks @vthiery ! Do you have any thoughs on what we should do when a new version of Stratus Red team gets released? I.s. how to bump the asdf version, and how we could automate this?

**Comment by vthiery** [comment]
@christophetd there is nothing to do from your side as the asdf plugin will be able to retrieve all the releases, including the "latest" as soon as it's released.

As a user, one can simply use `asdf install stratus-red-team latest` to get the latest release.
If one want a specific version, `asdf install stratus-red-team 2.15.0` would be the way to go.
Users may also do `asdf list all stratus-red-team` to list all the versions available.

Bonus tip: one can shorten the plugin name when adding it to avoid repeating "stratus-red-team". E.g. `asdf plugin add stratus https://github.com/asdf-community/asdf-stratus-red-team.git` and then `asdf list all stratus`.

**Comment by christophetd** [comment]
Amazing! Thanks for all the work around this

**Review by christophetd — APPROVED** [review]

**Pull request merged**
