### PR TITLE
New attack technique: Create ClusterAdmin role

### PR DESCRIPTION
**Pull request by christophetd**
### What does this PR do?

Introduce a new TTP
### Checklist

- [x] The attack technique emulates a single attack step, not a full attack chain
- [x] We have factual evidence & references that the attack technique was used by real malware, pentesters, or attackers - common privesc / persistence TTP
- [x] The attack technique makes no assumption about the state of the environment prior to warming it up

### Discussion points

- Should this be privesc or persistence?

### Sample output

```
2022/02/07 23:28:36 Checking your authentication against Kubernetes
2022/02/07 23:28:36 Creating Cluster Role stratus-red-team-clusterrole
2022/02/07 23:28:36 Creating Service Account stratus-red-team-serviceaccount
2022/02/07 23:28:36 Creating Cluster Role Binding to map the service account to the cluster role
2022/02/07 23:28:36 Successfully generate service account token:

eyJhbGciO...
```

Decoding to:

image

### CODE REVIEW

**Comment by christophetd** [comment]
closes #97

**Review by xen0ldog — APPROVED** [review]

**Comment by mccormickt** [comment]
This looks great!  For what it's worth, I would keep this as persistence.  

The way I see it, if you have credentials to create a cluster-admin role, you are already cluster-admin, so no escalation takes place.

**Review by mccormickt — APPROVED** [review]

**Comment by christophetd** [comment]
I tend to agree with you @mccormickt, I'm unsure because Microsoft puts it under Privesc: https://www.microsoft.com/security/blog/uploads/securityprod/2021/07/Threat-matrix-for-Kubernetes.png  

Also, how would you _actually_ use this for persistence? You can steal a service account token for this ClusterRole, but it's temporary (max X hours if I recall correctly). So is it really a good fit for persistence?

**Comment by raesene** [comment]
So a couple of thoughts. Generally I'd say it is persistence, not privilege escalation but there's some nuances.

It *could* be privilege escalation if your initial account just as the `bind` RBAC right, which allows for bindings which increase rights (which are generally blocked) but that's a bit niche :)

On the persistence, it'll depend on how the service account tokens are being managed. The "traditional" system creates a secret at the time of account creation and those secrets don't have expiry, but the new version (1.20 and up) has a short expiry by default. At the moment the old non-expiring secrets are still getting created though (so an attacker who can GET the secret can still retrieve and use it), but I believe the intention is to stop that at some point in the future :)

**Comment by christophetd** [comment]
Thanks for your input @raesene! That was exactly my thoughts, since TokenRequest (i.e. [here](https://github.com/DataDog/stratus-red-team/pull/96/files#diff-0b083c738065db83d7abd1dc0770d9a8a697bd6df1c738fd030c7081ae8092bcR85-R96)) cannot be made for more than a few hours (I don't recall the exact number).

If we keep persistence, I think it would make sense for the TTP to go and read the associated secret (`kubectl get secrets/stratus-red-team-serviceaccount-token-x2bvj -n kube-system -o yaml`), which indeed has no expiration. Thoughts?

**Comment by raesene** [comment]
yep watching for GET or LIST on secrets would seem like a good plan as either can reveal the contents of the non-expiring tokens

**Comment by christophetd** [comment]
Implemented in [0f23b2d](https://github.com/DataDog/stratus-red-team/pull/96/commits/0f23b2db2b3df1e080dac899f29b44c30390f51b): after creating the service account, I wait for its associated secret to be available, then read it. Recategorized under persistence.

Sample output:

```
2022/02/09 11:02:01 Checking your authentication against Kubernetes
2022/02/09 11:02:01 Creating Cluster Role stratus-red-team-clusterrole
2022/02/09 11:02:01 Creating Service Account stratus-red-team-serviceaccount
2022/02/09 11:02:01 Creating Cluster Role Binding to map the service account to the cluster role
2022/02/09 11:02:01 Finding secret associated to the newly created service account
2022/02/09 11:02:02 Stealing permanent service account token for this service account
2022/02/09 11:02:02 Successfully retrieved the service account token:

eyJhbGciOiJSUzI1NiIsImt...
```

Confirmed the JWT has no expiration:

```json
{
    "iss": "kubernetes/serviceaccount",
    "kubernetes.io/serviceaccount/namespace": "kube-system",
    "kubernetes.io/serviceaccount/secret.name": "stratus-red-team-serviceaccount-token-h6hhl",
    "kubernetes.io/serviceaccount/service-account.name": "stratus-red-team-serviceaccount",
    "kubernetes.io/serviceaccount/service-account.uid": "0ed47b5a-ba4c-4ccc-b52d-6775af2292c3",
    "sub": "system:serviceaccount:kube-system:stratus-red-team-serviceaccount"
}
```

**Pull request merged**
